spring:
  redis:
    host: #redis链接
    port: 6379
    # [可选] 数据库 DB
    database: 0
    password: #此处填写redis密码
    jedis:
      pool:
        max-active: 100
        min-idle: 50
        max-idle: -1

